[package]
name = "unrvl-risk"
description = "Risk measures and analytical tools for financial data"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"

[dependencies]

[lints]
workspace = true
