[package]
name = "test-utils"
description = "Shared testing utilities"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"
publish = false

[dependencies]
proptest.workspace = true

[dev-dependencies]

[lints]
workspace = true
