[package]
name = "reference-data"
description = "Test reference data and loaders"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"
publish = false

[dependencies]

[lints]
workspace = true
